### ISSUE TITLE
Functions won't start because socket file is missing.

### ISSUE THREAD

**Issue by TheBigLee** [vshn/appcat-comp-functions#28]
If the socket file is missing, the functions don't work (side car container will fail to start) and the following error will be shown:
`2023/04/21 00:56:50 stat @crossplane/fn/default.sock: no such file or directory`

The problem is in the following line:
https://github.com/vshn/appcat-comp-functions/blob/db776d3c662f84285eeaec4458f26ab1098ff666/main.go#L117

It should be adjusted to not fail if the socket file does not exist.

**Comment by wejdross** [comment]
ok, I'll fix it, I added code snippet suggested by Fabian without testing it properly

**Comment by wejdross** [comment]
fixed
